apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarn-opterator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yarn-opterator
  template:
    metadata:
      labels:
        name: yarn-opterator
    spec:
      serviceAccountName: yarn-opterator
      containers:
        - name: yarn-opterator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - yarn-opterator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "yarn-opterator"
