kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yarn-opterator
subjects:
- kind: ServiceAccount
  name: yarn-opterator
roleRef:
  kind: Role
  name: yarn-opterator
  apiGroup: rbac.authorization.k8s.io
