// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSource) DeepCopyInto(out *ClusterSource) {
	*out = *in
	if in.MapReduceCluster != nil {
		in, out := &in.MapReduceCluster, &out.MapReduceCluster
		*out = new(MapReduceClusterSource)
		**out = **in
	}
	if in.TEMapReduceCluster != nil {
		in, out := &in.TEMapReduceCluster, &out.TEMapReduceCluster
		*out = new(TEMapReduceClusterSource)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSource.
func (in *ClusterSource) DeepCopy() *ClusterSource {
	if in == nil {
		return nil
	}
	out := new(ClusterSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapReduceClusterSource) DeepCopyInto(out *MapReduceClusterSource) {
	*out = *in
	out.Config = in.Config
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapReduceClusterSource.
func (in *MapReduceClusterSource) DeepCopy() *MapReduceClusterSource {
	if in == nil {
		return nil
	}
	out := new(MapReduceClusterSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapReduceConfig) DeepCopyInto(out *MapReduceConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapReduceConfig.
func (in *MapReduceConfig) DeepCopy() *MapReduceConfig {
	if in == nil {
		return nil
	}
	out := new(MapReduceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagerSet) DeepCopyInto(out *NodeManagerSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagerSet.
func (in *NodeManagerSet) DeepCopy() *NodeManagerSet {
	if in == nil {
		return nil
	}
	out := new(NodeManagerSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeManagerSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagerSetList) DeepCopyInto(out *NodeManagerSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeManagerSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagerSetList.
func (in *NodeManagerSetList) DeepCopy() *NodeManagerSetList {
	if in == nil {
		return nil
	}
	out := new(NodeManagerSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeManagerSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagerSetSpec) DeepCopyInto(out *NodeManagerSetSpec) {
	*out = *in
	if in.Excludes != nil {
		in, out := &in.Excludes, &out.Excludes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Template.DeepCopyInto(&out.Template)
	in.ClusterSource.DeepCopyInto(&out.ClusterSource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagerSetSpec.
func (in *NodeManagerSetSpec) DeepCopy() *NodeManagerSetSpec {
	if in == nil {
		return nil
	}
	out := new(NodeManagerSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagerSetStatus) DeepCopyInto(out *NodeManagerSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagerSetStatus.
func (in *NodeManagerSetStatus) DeepCopy() *NodeManagerSetStatus {
	if in == nil {
		return nil
	}
	out := new(NodeManagerSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEMapReduceClusterSource) DeepCopyInto(out *TEMapReduceClusterSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEMapReduceClusterSource.
func (in *TEMapReduceClusterSource) DeepCopy() *TEMapReduceClusterSource {
	if in == nil {
		return nil
	}
	out := new(TEMapReduceClusterSource)
	in.DeepCopyInto(out)
	return out
}
